### ISSUE TITLE
Wiring

### ISSUE THREAD

**Issue by Ralle001** [sebdehne/DehneEVSE-Hardware#2]
Can you tell me which wire goes where?
Because it is really confusing from the type to till the pcb

**Comment by sebdehne** [comment]
Did you check the [schematic](https://github.com/sebdehne/DehneEVSE-Hardware/blob/master/Media/schematic.pdf), the [PCB](https://github.com/sebdehne/DehneEVSE-Hardware/blob/master/Media/PCB-3d-view.png) and the [description](https://dehnes.com/electronics/2021/03/31/dehneevse_charging_station.html) on my blog? 

It is not clear which wires you need help connecting. And please do not raise this type of questions as an issue; thanks

**Comment by Ralle001** [comment]
I might be blind, but I still cant see these cables:
<img width="1248" alt="Screenshot 2023-06-08 at 20 05 32" src="https://github.com/sebdehne/DehneEVSE-Hardware/assets/27433872/fff54903-ec16-4bd5-a670-36bb478ed230">

**Comment by sebdehne** [comment]
Incoming power (1, 2 or 3 phase) -> Type-B GFCI -> Contactor -> Type2 socket

But hey, if you do not know how to connect those wires, I think it is safest if you ask an electrician to connect those wires for you.
